// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Demo Supabase credentials (safe for public use - anon key is client-side safe)
// These are hardcoded to work with Lovable's preview environment
// 
// To use your own Supabase instance:
// 1. Create a new project at https://supabase.com
// 2. Replace the values below with your project's URL and anon key
// 3. Update the database schema to match (see supabase/migrations/)
const SUPABASE_URL = "https://nhqlaikoiyqmwsxqjorn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_cs0BK-FcZHqzX1OIlGNOpA_SX8lFzfT";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});